import { CalendarClock, CheckCircle2, Circle, Edit3, Plus, Trash2 } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Modal } from '../components/Modal';
import { useWorkspace } from '../context/WorkspaceContext';
import { api } from '../lib/api';
import type { Lead, Member, Task } from '../types';

const emptyForm={title:'',description:'',status:'TODO' as Task['status'],priority:'MEDIUM' as Task['priority'],dueDate:'',assigneeId:'',leadId:''};
const columns:Task['status'][]=['TODO','IN_PROGRESS','DONE'];
const names={TODO:'To do',IN_PROGRESS:'In progress',DONE:'Done'} as const;
export function TasksPage(){
 const {activeOrg}=useWorkspace(); const [tasks,setTasks]=useState<Task[]>([]);const [members,setMembers]=useState<Member[]>([]);const [leads,setLeads]=useState<Lead[]>([]);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Task|null>(null);const [form,setForm]=useState(emptyForm);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function load(){if(!activeOrg)return;const [t,m,l]=await Promise.all([api<{tasks:Task[]}>('/tasks',{orgId:activeOrg.id}),api<{members:Member[]}>(`/orgs/${activeOrg.id}/members`),api<{leads:Lead[]}>('/leads',{orgId:activeOrg.id})]);setTasks(t.tasks);setMembers(m.members);setLeads(l.leads)} useEffect(()=>{void load()},[activeOrg?.id]);
 const grouped=useMemo(()=>Object.fromEntries(columns.map(c=>[c,tasks.filter(t=>t.status===c)])) as Record<Task['status'],Task[]>,[tasks]);
 function startCreate(){setEditing(null);setForm(emptyForm);setError('');setOpen(true)} function startEdit(t:Task){setEditing(t);setForm({title:t.title,description:t.description||'',status:t.status,priority:t.priority,dueDate:t.dueDate?new Date(t.dueDate).toISOString().slice(0,16):'',assigneeId:t.assigneeId||'',leadId:t.leadId||''});setError('');setOpen(true)}
 async function submit(e:FormEvent){e.preventDefault();if(!activeOrg)return;setBusy(true);setError('');try{const payload={...form,dueDate:form.dueDate?new Date(form.dueDate).toISOString():null,assigneeId:form.assigneeId||null,leadId:form.leadId||null};if(editing)await api(`/tasks/${editing.id}`,{method:'PATCH',orgId:activeOrg.id,body:JSON.stringify(payload)});else await api('/tasks',{method:'POST',orgId:activeOrg.id,body:JSON.stringify(payload)});setOpen(false);await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 async function quickStatus(t:Task,status:Task['status']){if(!activeOrg)return;await api(`/tasks/${t.id}`,{method:'PATCH',orgId:activeOrg.id,body:JSON.stringify({status})});await load()}
 async function remove(t:Task){if(!activeOrg||!confirm(`Delete task “${t.title}”?`))return;await api(`/tasks/${t.id}`,{method:'DELETE',orgId:activeOrg.id});await load()}
 return <div className="content-page"><div className="page-head"><div><span className="eyebrow dark">Execution board</span><h1>Tasks</h1><p>Coordinate follow-ups and keep every opportunity moving.</p></div><button className="btn primary" onClick={startCreate}><Plus size={17}/>New task</button></div>
 <div className="kanban">{columns.map(col=><section className="kanban-col" key={col}><div className="kanban-head"><div><span className={`kanban-dot ${col.toLowerCase()}`}/><strong>{names[col]}</strong></div><span>{grouped[col].length}</span></div><div className="kanban-stack">{grouped[col].map(t=><article className="task-card" key={t.id}><div className="task-top"><span className={`badge priority ${t.priority.toLowerCase()}`}>{t.priority}</span><div className="row-actions"><button className="icon-btn" onClick={()=>startEdit(t)}><Edit3 size={15}/></button><button className="icon-btn danger" onClick={()=>remove(t)}><Trash2 size={15}/></button></div></div><h3>{t.title}</h3>{t.description&&<p>{t.description}</p>}{t.lead&&<span className="task-link">Lead: {t.lead.name}</span>}<div className="task-meta"><span><CalendarClock size={14}/>{t.dueDate?new Date(t.dueDate).toLocaleDateString():'No due date'}</span><span>{t.assignee?.name||'Unassigned'}</span></div><div className="task-status-actions">{col!=='TODO'&&<button onClick={()=>quickStatus(t,'TODO')}><Circle size={14}/>To do</button>}{col!=='IN_PROGRESS'&&<button onClick={()=>quickStatus(t,'IN_PROGRESS')}><CalendarClock size={14}/>Progress</button>}{col!=='DONE'&&<button onClick={()=>quickStatus(t,'DONE')}><CheckCircle2 size={14}/>Done</button>}</div></article>)}</div></section>)}</div>
 <Modal open={open} title={editing?'Edit task':'Create task'} onClose={()=>setOpen(false)}><form className="modal-form" onSubmit={submit}>{error&&<div className="alert error">{error}</div>}<label>Task title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Description<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-grid"><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Task['status']})}>{columns.map(c=><option key={c} value={c}>{names[c]}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Task['priority']})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label>Due date<input type="datetime-local" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Assignee<select value={form.assigneeId} onChange={e=>setForm({...form,assigneeId:e.target.value})}><option value="">Unassigned</option>{members.map(m=><option key={m.user.id} value={m.user.id}>{m.user.name}</option>)}</select></label></div><label>Related lead<select value={form.leadId} onChange={e=>setForm({...form,leadId:e.target.value})}><option value="">No related lead</option>{leads.map(l=><option key={l.id} value={l.id}>{l.name} {l.company?`— ${l.company}`:''}</option>)}</select></label><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" disabled={busy}>{busy?'Saving…':'Save task'}</button></div></form></Modal>
 </div>
}
